#!/usr/bin/env python3
"""
DESCRIPTION:

SUBSCRIBERS:
"""

from __future__ import division
import rclpy
from rclpy.node import Node
import numpy as np
from mini_interfaces.msg import MiniCmd, JoyButtons, IMUdata, ContactData, AgentData, JointAngles
import copy
import sys
import os

from ament_index_python.packages import get_package_share_directory
sys.path.append(get_package_share_directory('mini_ros2') + '/../')

# for spotmicro stuff
sys.path.append('../')

from spotmicro.Kinematics.SpotKinematics import SpotModel
from spotmicro.GaitGenerator.Bezier import BezierGait
from spot_bullet.src.ars_lib.ars import ARSAgent, Normalizer, Policy
from spotmicro.GymEnvs.spot_bezier_env import spotBezierEnv

class SpotCommander(Node):
    def __init__(self, Agent=True, contacts=False):
        super().__init__('Policies') # was anonymous in ROS1

        self.declare_parameter("agent_num", 0)
        self.declare_parameter("BaseStepVelocity", 0.001)
        self.declare_parameter("Tswing", 0.2)
        self.declare_parameter("SwingPeriod_LIMITS", [0.1, 0.3])
        self.declare_parameter("BaseClearanceHeight", 0.035)
        self.declare_parameter("BasePenetrationDepth", 0.003)
        self.declare_parameter("ClearanceHeight_LIMITS", [0.0, 0.04])
        self.declare_parameter("PenetrationDepth_LIMITS", [0.0, 0.02])
        self.declare_parameter("shoulder_length", 0.055)
        self.declare_parameter("elbow_length", 0.10652)
        self.declare_parameter("wrist_length", 0.145)
        self.declare_parameter("hip_x", 0.23)
        self.declare_parameter("hip_y", 0.075)
        self.declare_parameter("foot_x", 0.23)
        self.declare_parameter("foot_y", 0.185)
        self.declare_parameter("height", 0.20)
        self.declare_parameter("com_offset", 0.0)
        self.declare_parameter("dt", 0.001)

        self.declare_parameter("STEPLENGTH_SCALE", 0.05)
        self.declare_parameter("Z_SCALE_CTRL", 0.15)
        self.declare_parameter("RPY_SCALE", 0.785)
        self.declare_parameter("SV_SCALE", 0.05)
        self.declare_parameter("CHPD_SCALE", 0.0005)
        self.declare_parameter("YAW_SCALE", 1.25)

        self.declare_parameter("CD_SCALE", 0.05)
        self.declare_parameter("SLV_SCALE", 0.05)
        self.declare_parameter("RESIDUALS_SCALE", 0.015)
        self.declare_parameter("Z_SCALE", 0.035)
        self.declare_parameter("alpha", 0.7)
        self.declare_parameter("actions_to_filter", 14)


        # Controller Params
        self.STEPLENGTH_SCALE = self.get_parameter("STEPLENGTH_SCALE").value
        self.Z_SCALE_CTRL = self.get_parameter("Z_SCALE_CTRL").value
        self.RPY_SCALE = self.get_parameter("RPY_SCALE").value
        self.SV_SCALE = self.get_parameter("SV_SCALE").value
        self.CHPD_SCALE = self.get_parameter("CHPD_SCALE").value
        self.YAW_SCALE = self.get_parameter("YAW_SCALE").value

        # AGENT PARAMS
        self.CD_SCALE = self.get_parameter("CD_SCALE").value
        self.SLV_SCALE = self.get_parameter("SLV_SCALE").value
        self.RESIDUALS_SCALE = self.get_parameter("RESIDUALS_SCALE").value
        self.Z_SCALE = self.get_parameter("Z_SCALE").value
        # Filter actions
        self.alpha = self.get_parameter("alpha").value
        # Added this to avoid filtering residuals
        # -1 for all
        self.actions_to_filter = self.get_parameter("actions_to_filter").value


        self.Agent = Agent
        self.agent_num = self.get_parameter("agent_num").value
        self.movetypes = ["Stop"]
        self.mini_cmd = MiniCmd()
        self.jb = JoyButtons()
        self.mini_cmd.x_velocity = 0.0
        self.mini_cmd.y_velocity = 0.0
        self.mini_cmd.rate = 0.0
        self.mini_cmd.roll = 0.0
        self.mini_cmd.pitch = 0.0
        self.mini_cmd.yaw = 0.0
        self.mini_cmd.z = 0.0
        self.mini_cmd.motion = "Stop"
        self.mini_cmd.movement = "Stepping"
        # FIXED
        self.BaseStepVelocity = self.get_parameter("BaseStepVelocity").value
        self.StepVelocity = copy.deepcopy(self.BaseStepVelocity)
        # Stock, use Bumpers to change
        self.BaseSwingPeriod = self.get_parameter("Tswing").value
        self.SwingPeriod = copy.deepcopy(self.BaseSwingPeriod)
        self.SwingPeriod_LIMITS = self.get_parameter("SwingPeriod_LIMITS").value
        # Stock, use arrow pads to change
        self.BaseClearanceHeight = self.get_parameter("BaseClearanceHeight").value
        self.BasePenetrationDepth = self.get_parameter("BasePenetrationDepth").value
        self.ClearanceHeight = copy.deepcopy(self.BaseClearanceHeight)
        self.PenetrationDepth = copy.deepcopy(self.BasePenetrationDepth)
        self.ClearanceHeight_LIMITS = self.get_parameter("ClearanceHeight_LIMITS").value
        self.PenetrationDepth_LIMITS = self.get_parameter("PenetrationDepth_LIMITS").value

        # Time
        self.time = (self.get_clock().now().nanoseconds / 1.0e9)

        self.enable_contact = contacts

        # Contacts: FL, FR, BL, BR
        self.contacts = [0, 0, 0, 0]

        # IMU: R, P, Ax, Ay, Az, Gx, Gy, Gz
        self.imu = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

        # See spot_params.yaml in config
        self.spot = SpotModel(
            shoulder_length=self.get_parameter("shoulder_length").value,
            elbow_length=self.get_parameter("elbow_length").value,
            wrist_length=self.get_parameter("wrist_length").value,
            hip_x=self.get_parameter("hip_x").value,
            hip_y=self.get_parameter("hip_y").value,
            foot_x=self.get_parameter("foot_x").value,
            foot_y=self.get_parameter("foot_y").value,
            height=self.get_parameter("height").value,
            com_offset=self.get_parameter("com_offset").value)

        self.T_bf0 = self.spot.WorldToFoot
        self.T_bf = copy.deepcopy(self.T_bf0)

        # See spot_params.yaml in config
        self.bzg = BezierGait(dt=self.get_parameter("dt").value,
                              Tswing=self.get_parameter("Tswing").value)

        if self.Agent:
            self.load_spot(contacts, agent_num=self.agent_num)
        
        # cmd_cb from mini_cmd topic
        self.sub_cmd = self.create_subscription(MiniCmd,
                                        'mini_cmd',
                                        self.cmd_cb,
                                        10)
        self.sub_jb = self.create_subscription(JoyButtons,
                                       'joybuttons',
                                       self.jb_cb,
                                       10)
        self.sub_imu = self.create_subscription(IMUdata,
                                        'spot/imu',
                                        self.imu_cb,
                                        10)
        self.sub_cnt = self.create_subscription(ContactData,
                                        'spot/contact',
                                        self.cnt_cb,
                                        10)
        self.ag_pub = self.create_publisher(AgentData, 'spot/agent', 10)
        self.ja_pub = self.create_publisher(JointAngles, 'spot/joints', 10)

        # timer callback for move control
        timer_period = 1.0/600.0
        self.timer = self.create_timer(timer_period, self.timer_callback)

        self.get_logger().info("READY TO GO!")

    def timer_callback(self):
        # this is called continuously
        self.move()

    def load_spot(self, contacts, state_dim=12, action_dim=14, agent_num=0):
        self.policy = Policy(state_dim=state_dim, action_dim=action_dim)
        self.normalizer = Normalizer(state_dim=state_dim)
        env = spotBezierEnv(render=False,
                            on_rack=False,
                            height_field=False,
                            draw_foot_path=False)
        agent = ARSAgent(self.normalizer, self.policy, env)
        my_path = os.path.abspath(os.path.dirname(__file__))
        if contacts:
            models_path = os.path.join(my_path,
                                       "../../../../../spot_bullet/models/contact")
        else:
            models_path = os.path.join(my_path,
                                       "../../../../../spot_bullet/models/no_contact")

        self.get_logger().info("MODEL PATH: {}".format(models_path))
        file_name = "spot_ars_"
        if os.path.exists(models_path + "/" + file_name + str(agent_num) +
                          "_policy"):
            self.get_logger().info("Loading Existing agent: {}".format(agent_num))
            agent.load(models_path + "/" + file_name + str(agent_num))
            agent.policy.episode_steps = np.inf
            self.policy = agent.policy

        self.action = np.zeros(action_dim)
        self.old_act = self.action[:self.actions_to_filter]

    def imu_cb(self, imu):
        """ Reads the IMU

            Args: imu
        """
        # Update imu
        self.imu = [
            imu.roll, imu.pitch,
            np.radians(imu.gyro_x),
            np.radians(imu.gyro_y),
            np.radians(imu.gyro_z), imu.acc_x, imu.acc_y, imu.acc_z - 9.81
        ]
        # log input data as debug-level message
        self.get_logger().debug(imu)


    def cnt_cb(self, cnt):
        """ Reads the Contact Sensors

            Args: cnt
        """
        # Update contacts
        self.contacts = [cnt.FL, cnt.FR, cnt.BL, cnt.BR]
        # log input data as debug-level message
        self.get_logger().debug(cnt)

    def cmd_cb(self, mini_cmd):
        """ Reads the desired Minitaur command and passes it for execution

            Args: mini_cmd
        """
        # Update mini_cmd
        self.mini_cmd = mini_cmd
        # log input data as debug-level message
        self.get_logger().debug(mini_cmd)

    def jb_cb(self, jb):
        """ Reads the desired additional joystick buttons

            Args: jb
        """
        # Update jb
        self.jb = jb
        # log input data as debug-level message
        self.get_logger().debug(jb)

    def move(self):
        """ Turn joystick inputs into commands
        """

        # Move Type
        if self.mini_cmd.movement == "Stepping":
            step_or_view = False
        else:
            step_or_view = True

        if self.mini_cmd.motion != "Stop":
            self.StepVelocity = copy.deepcopy(self.BaseStepVelocity)
            self.SwingPeriod = np.clip(
                copy.deepcopy(self.BaseSwingPeriod) +
                (-self.mini_cmd.faster + -self.mini_cmd.slower) * self.SV_SCALE,
                self.SwingPeriod_LIMITS[0], self.SwingPeriod_LIMITS[1])
            if self.mini_cmd.movement == "Stepping":
                # Only take 2/3 of lateral step length or it will be too great.
                StepLength = self.mini_cmd.x_velocity + abs(
                    self.mini_cmd.y_velocity * 0.66)
                StepLength = np.clip(StepLength, -1.0, 1.0)
                StepLength *= self.STEPLENGTH_SCALE
                # Convert lateral joystick action into poolar coordinates
                # for lateral movement
                LateralFraction = self.mini_cmd.y_velocity * np.pi / 2
                YawRate = self.mini_cmd.rate * self.YAW_SCALE
                # NOTE: NO HEIGHT MOD DURING WALK
                pos = np.array([0.0, 0.0, 0.0])
                orn = np.array([0.0, 0.0, 0.0])
            else:
                StepLength = 0.0
                LateralFraction = 0.0
                YawRate = 0.0
                # RESET
                self.ClearanceHeight = copy.deepcopy(self.BaseClearanceHeight)
                self.PenetrationDepth = copy.deepcopy(
                    self.BasePenetrationDepth)
                self.StepVelocity = copy.deepcopy(self.BaseStepVelocity)
                # x offset
                pos = np.array([0.0, 0.0, self.mini_cmd.z * self.Z_SCALE_CTRL])
                orn = np.array([
                    self.mini_cmd.roll * self.RPY_SCALE,
                    self.mini_cmd.pitch * self.RPY_SCALE,
                    self.mini_cmd.yaw * self.RPY_SCALE
                ])
        else:
            StepLength = 0.0
            LateralFraction = 0.0
            YawRate = 0.0
            # RESET
            self.ClearanceHeight = self.BaseClearanceHeight
            self.PenetrationDepth = self.BasePenetrationDepth
            self.StepVelocity = self.BaseStepVelocity
            self.SwingPeriod = self.BaseSwingPeriod
            pos = np.array([0.0, 0.0, 0.0])
            orn = np.array([0.0, 0.0, 0.0])

        # TODO: integrate into controller
        self.ClearanceHeight += self.jb.updown * self.CHPD_SCALE
        self.PenetrationDepth += self.jb.leftright * self.CHPD_SCALE

        # Manual Reset
        if self.jb.left_bump or self.jb.right_bump:
            self.ClearanceHeight = copy.deepcopy(self.BaseClearanceHeight)
            self.PenetrationDepth = copy.deepcopy(self.BasePenetrationDepth)
            self.StepVelocity = copy.deepcopy(self.BaseStepVelocity)
            self.SwingPeriod = copy.deepcopy(self.BaseSwingPeriod)

        # OPTIONAL: Agent
        if self.Agent and self.mini_cmd.motion != "Stop":
            phases = copy.deepcopy(self.bzg.Phases)
            # Total 12
            state = []
            # r, p, gz, gy, gz, ax, ay, az (8)
            state.extend(self.imu)
            # FL, FR, BL, BR (4)
            state.extend(phases)
            # FL, FR, BL, BR (4)
            if self.enable_contact:
                state.extend(self.contacts)
            self.normalizer.observe(state)
            # Don't normalize contacts
            state[:-4] = self.normalizer.normalize(state)[:-4]
            self.action = self.policy.evaluate(state, None, None)
            self.action = np.tanh(self.action)
            # EXP FILTER
            self.action[:self.actions_to_filter] = self.alpha * self.old_act + (
                1.0 - self.alpha) * self.action[:self.actions_to_filter]
            self.old_act = self.action[:self.actions_to_filter]

            self.ClearanceHeight += self.action[0] * self.CD_SCALE

        # Time
        dt = (self.get_clock().now().nanoseconds / 1.0e9) - self.time
        # self.get_logger().info("dt: {}".format(dt))
        self.time = (self.get_clock().now().nanoseconds / 1.0e9)

        # Update Step Period
        self.bzg.Tswing = self.SwingPeriod

        # CLIP
        self.ClearanceHeight = np.clip(self.ClearanceHeight,
                                       self.ClearanceHeight_LIMITS[0],
                                       self.ClearanceHeight_LIMITS[1])
        self.PenetrationDepth = np.clip(self.PenetrationDepth,
                                        self.PenetrationDepth_LIMITS[0],
                                        self.PenetrationDepth_LIMITS[1])

        self.T_bf = self.bzg.GenerateTrajectory(StepLength, LateralFraction,
                                                YawRate, self.StepVelocity,
                                                self.T_bf0, self.T_bf,
                                                self.ClearanceHeight,
                                                self.PenetrationDepth,
                                                self.contacts, dt)

        T_bf_copy = copy.deepcopy(self.T_bf)
        # OPTIONAL: Agent
        if self.Agent and self.mini_cmd.motion != "Stop":
            self.action[2:] *= self.RESIDUALS_SCALE
            # Add DELTA to XYZ Foot Poses
            T_bf_copy["FL"][:3, 3] += self.action[2:5]
            T_bf_copy["FR"][:3, 3] += self.action[5:8]
            T_bf_copy["BL"][:3, 3] += self.action[8:11]
            T_bf_copy["BR"][:3, 3] += self.action[11:14]
            pos[2] += abs(self.action[1]) * self.Z_SCALE

        joint_angles = self.spot.IK(orn, pos, T_bf_copy)

        ja_msg = JointAngles()

        ja_msg.fls = np.degrees(joint_angles[0][0])
        ja_msg.fle = np.degrees(joint_angles[0][1])
        ja_msg.flw = np.degrees(joint_angles[0][2])

        ja_msg.frs = np.degrees(joint_angles[1][0])
        ja_msg.fre = np.degrees(joint_angles[1][1])
        ja_msg.frw = np.degrees(joint_angles[1][2])

        ja_msg.bls = np.degrees(joint_angles[2][0])
        ja_msg.ble = np.degrees(joint_angles[2][1])
        ja_msg.blw = np.degrees(joint_angles[2][2])

        ja_msg.brs = np.degrees(joint_angles[3][0])
        ja_msg.bre = np.degrees(joint_angles[3][1])
        ja_msg.brw = np.degrees(joint_angles[3][2])

        # Move Type
        ja_msg.step_or_view = step_or_view

        self.ja_pub.publish(ja_msg)


def main(args = None):
    """ The main() function. """
    rclpy.init(args=args)

    mini_commander = SpotCommander()
    rclpy.spin(mini_commander)

    mini_commander.destroy_node()
    rclpy.shutdown()

if __name__ == '__main__':
    main()
